name: 🐞 รายงานบั๊ก
description: แจ้งปัญหาข้อผิดพลาดของระบบ
title: "[บั๊ก]: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        👋 ขอบคุณที่สละเวลามารายงานบั๊ก!
  - type: input
    id: contact
    attributes:
      label: ข้อมูลติดต่อ
      description: หากเราต้องการข้อมูลเพิ่มเติม จะติดต่อคุณได้อย่างไร?
      placeholder: your@email.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: เกิดอะไรขึ้น?
      description: กรุณาบอกเราด้วยว่าคุณคาดหวังให้เกิดอะไรขึ้นแทน
      placeholder: บอกเราว่าคุณเห็นอะไร!
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: ขั้นตอนการทำให้เกิดบั๊ก
      description: |
        กรุณาอธิบายวิธีที่เราจะสามารถทำให้เกิดบั๊กนี้ได้ทีละขั้นตอน
      placeholder: |
        1. ไปที่ '...'
        2. คลิกที่ '....'
        3. เลื่อนลงไปที่ '....'
        4. พบข้อผิดพลาด
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: สภาพแวดล้อมของระบบ
      description: |
        กรุณาแจ้งข้อมูลระบบที่คุณใช้งาน (OS, เบราว์เซอร์, เวอร์ชัน ฯลฯ)
      placeholder: |
        - ระบบปฏิบัติการ: [เช่น Windows 11, macOS 13.5]
        - เบราว์เซอร์: [เช่น Chrome 124, Safari, Firefox]
        - เวอร์ชันของโปรแกรม: [เช่น v1.0.0]
    validations:
      required: false