blank_issues_enabled: false
contact_links:
  - name: พูดคุยหรือสอบถามเพิ่มเติม
    url: https://github.com/lovely2550/gui/discussions
    about: ถ้าคุณมีคำถามทั่วไปหรืออยากพูดคุยเกี่ยวกับโปรเจกต์นี้ โปรดไปที่ Discussions แทนการสร้าง Issue