name: CI  # ชื่อ Workflow: การทดสอบแบบต่อเนื่อง (Continuous Integration)

on:  # เหตุการณ์ที่ทำให้ Workflow นี้ทำงาน
  push:  # เมื่อมีการ push โค้ดขึ้นมา
    branches: [main]  # เฉพาะสาขา main เท่านั้น
  pull_request:  # เมื่อมีการสร้าง pull request
    branches: [main]  # เฉพาะกับสาขา main เท่านั้น

jobs:  # งาน (job) ที่จะทำใน workflow นี้
  build:  # ชื่องานว่า build
    runs-on: ubuntu-latest  # ใช้ runner ระบบ Ubuntu เวอร์ชันล่าสุด

    steps:  # ขั้นตอนต่าง ๆ ในงานนี้
    - uses: actions/checkout@v2  # ขั้นตอนแรก ใช้ action เพื่อ checkout โค้ดจาก repo
    - name: Set up Python 3.8  # ตั้งชื่อขั้นตอนว่า ติดตั้ง Python 3.8
      uses: actions/setup-python@v2  # ใช้ action ติดตั้ง Python
      with:
        python-version: 3.8  # กำหนดเวอร์ชัน Python เป็น 3.8

    - name: Install dependencies  # ขั้นตอนติดตั้ง dependencies หรือไลบรารีที่จำเป็น
      run: |
        python -m pip install --upgrade pip  # อัปเกรด pip ให้เป็นเวอร์ชันล่าสุด
        pip install -r requirements.txt  # ติดตั้งแพ็กเกจตามไฟล์ requirements.txt

    - name: Run tests  # ขั้นตอนรันการทดสอบโค้ด
      run: |
        pytest  # ใช้ pytest รัน unit test ทั้งหมด